changelog:
  exclude:
    labels:
      - ignore-for-release
  categories:
    - title: Breaking Changes
      labels:
        - major
        - text-field
    - title: Features
      labels:
        - minor
        - text-field
    - title: Bugfixes
      labels:
        - patch
        - text-field
    - title: Dependency updates
      labels:
        - dependencies
